# .github/workflows/build-blog.yml
name: Build Blog

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'templates/**'
      - 'public/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown pyyaml
    
    - name: Build blog
      run: python blog_generator.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
